Repository KoalaFacade/diamond-console, pull requests merged in 2022-12, with the labels that each got.

#17 build(command): add command to create enum
  src/Commands/MakeEnumCommand.php
  stubs/enum.stub
  tests/Feature/Commands/MakeEnumTest.php
Labels: enhancement

#19 docs: update base docs
  README.md
Labels: documentation

#25 refactor(core): reduce complexity by heart
  src/Actions/Filesystem/FilePresentAction.php
  src/Actions/Stub/CopyStubAction.php
  src/Actions/Stub/ReplacePlaceholderAction.php
  src/Commands/Concerns/HasArguments.php
  src/Commands/Concerns/HasOptions.php
  src/Commands/Concerns/InteractsWithPath.php
  src/Commands/MakeActionCommand.php
  src/Commands/MakeDtoCommand.php
  src/Commands/MakeEnumCommand.php
  src/Commands/MakeMailCommand.php
  src/Commands/MakeMigrationCommand.php
  src/Commands/MakeModelCommand.php
  src/DataTransferObjects/CopyStubData.php
  src/DataTransferObjects/Filesystem/FilePresentData.php
  src/DataTransferObjects/PlaceholderData.php
  src/Foundation/DataTransferObject/HasArrayable.php
  tests/Feature/Commands/MakeDtoTest.php
Labels: enhancement

#26 Factory commands
  README.md
  src/Commands/Concerns/HasOptions.php
  src/Commands/Concerns/InteractsWithPath.php
  src/Commands/MakeFactoryCommand.php
  src/Commands/MakeMailCommand.php
  src/Commands/MakeModelCommand.php
  src/Contracts/Factory.php
  src/DataTransferObjects/PlaceholderData.php
  src/Foundation/CreateNewFactory.php
  stubs/factory-contract.stub
  stubs/factory.stub
  stubs/model-factory.stub
  tests/Feature/Commands/GenerateActionTest.php
  tests/Feature/Commands/GenerateDtoTest.php
  tests/Feature/Commands/GenerateEnumTest.php
  tests/Feature/Commands/GenerateFactoryTest.php
  tests/Feature/Commands/GenerateMailTest.php
  tests/Feature/Commands/GenerateMigrationTest.php
  tests/Feature/Commands/GenerateModelTest.php
  tests/Feature/Commands/InstallBaseStructureCommandTest.php
  tests/Pest.php
Labels: enhancement

#29 docs: add table of contents
  README.md
Labels: documentation

#30 docs: argument to arguments
  README.md
Labels: documentation

#34 style: remove prefix Contract on factory class
  src/Commands/MakeFactoryCommand.php
  src/Commands/MakeModelCommand.php
  stubs/factory.stub
  stubs/model-factory.stub
  tests/Feature/Commands/GenerateFactoryTest.php
  tests/Feature/Commands/GenerateModelTest.php
Labels: documentation

#35 refactor(command): change signature and update description
  src/Commands/MakeActionCommand.php
  src/Commands/MakeDTOCommand.php
  src/Commands/MakeEnumCommand.php
  src/Commands/MakeFactoryCommand.php
  src/Commands/MakeMailCommand.php
  src/Commands/MakeMigrationCommand.php
  src/Commands/MakeModelCommand.php
  tests/Feature/Commands/GenerateActionTest.php
  tests/Feature/Commands/GenerateDTOTest.php
  tests/Feature/Commands/GenerateEnumTest.php
  tests/Feature/Commands/GenerateFactoryTest.php
  tests/Feature/Commands/GenerateMailTest.php
  tests/Feature/Commands/GenerateMigrationTest.php
  tests/Feature/Commands/GenerateModelTest.php
Labels: documentation

#36 Improve documentation with new command signature
  README.md
Labels: documentation

#37 Improve code base
  composer.json
  src/Actions/Stub/ReplacePlaceholderAction.php
  src/DataTransferObjects/PlaceholderData.php
  src/Foundation/DataTransferObject.php
  src/Foundation/DataTransferObject/HasArrayable.php
  src/Foundation/EvaluatesClosures.php
  stubs/factory.stub
  stubs/migration-create.stub
  stubs/migration-table.stub
  stubs/model-factory.stub
Labels: documentation

#39 Introduce seeder command
  src/Commands/Concerns/InteractsWithPath.php
  src/Commands/MakeFactoryCommand.php
  src/Commands/MakeSeederCommand.php
  stubs/seeder.stub
  tests/Feature/Commands/GenerateActionTest.php
  tests/Feature/Commands/GenerateDTOTest.php
  tests/Feature/Commands/GenerateEnumTest.php
  tests/Feature/Commands/GenerateFactoryTest.php
  tests/Feature/Commands/GenerateMailTest.php
  tests/Feature/Commands/GenerateModelTest.php
  tests/Feature/Commands/GenerateSeederTest.php
  tests/Feature/Commands/GenerateValueObjectTest.php
Labels: enhancement

#45 Refactor package to PHP 8.2 and Introduce standard DTO and Action to readonly
  src/Actions/Command/ResolveCommandAction.php
  src/Actions/Composer/ResolveComposerAutoLoaderAction.php
  src/Actions/Factory/FactoryContractMakeAction.php
  src/Actions/Filesystem/FilePresentAction.php
  src/Actions/Stub/CopyStubAction.php
  src/Actions/Stub/ReplacePlaceholderAction.php
  src/Commands/Concerns/InteractsWithConsole.php
  src/Commands/FactoryMakeCommand.php
  src/DataTransferObjects/CopyStubData.php
  src/DataTransferObjects/Filesystem/FilePresentData.php
  src/DataTransferObjects/PlaceholderData.php
  src/DiamondConsoleServiceProvider.php
  src/Foundation/Action.php
  src/Foundation/DataTransferObject.php
  src/Foundation/EvaluatesClosures.php
  stubs/data-transfer-object.stub
Labels: enhancement

#47 fix(stub): missing semicolon, conflict class, unused import
  stubs/factory.stub
Labels: enhancement

#48 build(command): add command to create Observer
  src/Commands/ObserverMakeCommand.php
  stubs/observer.stub
  tests/Feature/Commands/ObserverMakeCommandTest.php
Labels: enhancement

#49 refactor(test): make the same structure code
  tests/Feature/Commands/ActionMakeCommandTest.php
  tests/Feature/Commands/DataTransferObjectMakeCommandTest.php
  tests/Feature/Commands/EnumMakeCommandTest.php
  tests/Feature/Commands/FactoryMakeCommandTest.php
  tests/Feature/Commands/MailMakeCommandTest.php
  tests/Feature/Commands/MigrationMakeCommandTest.php
  tests/Feature/Commands/ModelMakeCommandTest.php
  tests/Feature/Commands/ObserverMakeCommandTest.php
  tests/Feature/Commands/ProviderMakeCommandTest.php
  tests/Feature/Commands/SeederMakeCommandTest.php
  tests/Feature/Commands/ValueObjectMakeCommandTest.php
  tests/Pest.php
Labels: documentation

#50 docs: introduce new command and improve badge
  README.md
Labels: documentation

#53 build(command): add command to create Listener
  README.md
  src/Commands/Concerns/HasOptions.php
  src/Commands/ListenerMakeCommand.php
  src/DataTransferObjects/PlaceholderData.php
  stubs/listener-event.stub
  stubs/listener.stub
  tests/Feature/Commands/ListenerMakeCommandTest.php
Labels: enhancement

#54 fix(stub): missing semicolon and phpdoc indent
  stubs/model-factory.stub
Labels: bug

#55 refactor(docs): order command list by name and group by type
  README.md
Labels: documentation

#57 build(command): add command to create Request
  README.md
  src/Commands/RequestMakeCommand.php
  src/Support/Source.php
  stubs/request.stub
  tests/Feature/Commands/RequestMakeCommandTest.php
  tests/Pest.php
Labels: enhancement

#58 refactor(command): allow null endsWith argumrnt on `getNamespace()`
  src/Commands/RequestMakeCommand.php
  src/DataTransferObjects/NamespaceData.php
  src/Support/Source.php
Labels: documentation

#59 refactor(command): migration to diamond instead of application
  README.md
  src/Commands/MigrationMakeCommand.php
  src/Commands/ModelMakeCommand.php
  tests/Feature/Commands/MigrationMakeCommandTest.php
  tests/Feature/Commands/ModelMakeCommandTest.php
  tests/Pest.php
Labels: documentation

#60 fix(command): namespace not uppercase in first on application layer
  src/Commands/RequestMakeCommand.php
Labels: bug

#61 build(command): add command to create Resource
  README.md
  src/Commands/Concerns/HasOptions.php
  src/Commands/ResourceMakeCommand.php
  src/DataTransferObjects/PlaceholderData.php
  stubs/resource.stub
  tests/Feature/Commands/ResourceMakeCommandTest.php
  tests/Pest.php
Labels: enhancement

#62 build(command): add command to create Query Builder
  README.md
  src/Commands/BuilderMakeCommand.php
  src/Commands/Concerns/HasOptions.php
  src/Commands/ResourceMakeCommand.php
  stubs/builder-model.stub
  stubs/builder.stub
  tests/Feature/Commands/BuilderMakeCommandTest.php
Labels: enhancement

#63 style(stub): remove return void on construct
  stubs/event.stub
  stubs/listener-event.stub
  stubs/listener.stub
  stubs/mail.stub
Labels: bug
