Repository KoalaFacade/diamond-console, pull requests merged in 2023-02, with the labels that each got.

#68 Buil: laravel 10 support
  .github/workflows/run-test.yml
  README.md
  composer.json
Labels: enhancement

#69 Fix: workflow for multiple version
  .github/workflows/run-test.yml
Labels: bug

#70 refactor(commands): tidy up command directory and refactor application command
  composer.json
  src/Commands/Application/Concerns/InteractsWithConsoleInApplication.php
  src/Commands/Application/RequestMakeCommand.php
  src/Commands/Application/ResourceMakeCommand.php
  src/Commands/Domain/ActionMakeCommand.php
  src/Commands/Domain/BuilderMakeCommand.php
  src/Commands/Domain/DataTransferObjectMakeCommand.php
  src/Commands/Domain/EnumMakeCommand.php
  src/Commands/Domain/ModelMakeCommand.php
  src/Commands/Domain/ValueObjectMakeCommand.php
  src/Commands/Infrastructure/EventMakeCommand.php
  src/Commands/Infrastructure/FactoryMakeCommand.php
  src/Commands/Infrastructure/ListenerMakeCommand.php
  src/Commands/Infrastructure/MailMakeCommand.php
  src/Commands/Infrastructure/ObserverMakeCommand.php
  src/Commands/Infrastructure/ProviderMakeCommand.php
  src/Commands/Infrastructure/SeederMakeCommand.php
  src/Commands/InstallCommand.php
  src/DiamondConsoleServiceProvider.php
  src/Enums/Layer.php
Labels: refactor

#71 docs: migrate usage case docs to official docs
  README.md
Labels: documentation

#72 fix: DTO generated at the wrong place should be present in application layer
  composer.json
  src/Commands/Application/DataTransferObjectMakeCommand.php
  tests/Feature/Commands/Application/DataTransferObjectMakeCommandTest.php
  tests/Feature/Commands/Application/RequestMakeCommandTest.php
  tests/Feature/Commands/Application/ResourceMakeCommandTest.php
  tests/Feature/Commands/DataTransferObjectMakeCommandTest.php
  tests/Feature/Commands/Domain/ActionMakeCommandTest.php
  tests/Feature/Commands/Domain/BuilderMakeCommandTest.php
  tests/Feature/Commands/Domain/EnumMakeCommandTest.php
  tests/Feature/Commands/Domain/ModelMakeCommandTest.php
  tests/Feature/Commands/Domain/ValueObjectMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/EventMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/FactoryMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/ListenerMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/MailMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/ObserverMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/ProviderMakeCommandTest.php
  tests/Feature/Commands/Infrastructure/SeederMakeCommandTest.php
  tests/Pest.php
Labels: enhancement, refactor

#73 Fix Data Transfer Object generate wrong namespace app got to App instead of app
  src/Commands/Application/Concerns/InteractsWithConsoleInApplication.php
  src/Commands/Application/DataTransferObjectMakeCommand.php
  src/Commands/Application/RequestMakeCommand.php
Labels: bug, refactor

#76 fix(installation): skip create app path in src directory
  src/Commands/InstallCommand.php
  tests/Feature/Commands/InstallBaseStructureCommandTest.php
Labels: bug

#77 Refactor DTO using cuyz/valinor to better implementation
  composer.json
  src/Foundation/DataTransferObject.php
  src/Foundation/DataTransferObject/HasResolvable.php
  tests/Unit/DataTransferObjects/DataTransferObjectTest.php
  tests/Unit/DataTransferObjects/Fixtures/GenderEnum.php
  tests/Unit/DataTransferObjects/Fixtures/RoleData.php
  tests/Unit/DataTransferObjects/Fixtures/UserData.php
Labels: enhancement, refactor
